### ISSUE TITLE
Coordinate Between the PSF Finance Team and the PyLadies Finance Team for Work Group Meetings

### ISSUE THREAD

**Issue by BethanyG** [pyladies/global-organizing#106]
* Schedule next meeting in 2 weeks 16th feb, 17th feb when all 3 accountant’s are available 
* lets also ask the global council and lorena who else would like to attend
*  let’s share the doodle link with other members, also they can add dates to the follow if these dates don’t work for everyone

**Comment by Marie-L** [comment]
The meeting was scheduled on 24th feb therefore, I will close this issue.
