### ISSUE TITLE
Draft diversity statement

### ISSUE THREAD

**Issue by MmeMarieLouise** [pyladies/global-organizing#122]
# Tasks
- [ ] Draft stop asian hate statement
- [ ] GC review
- [ ] GA review
- [ ] publish

## Diversity and Inclusion guidance for chapters

- [ ] Draft D&I CoC

cc/ @pyladies/pyladies-global-admin

**Comment by Marie-L** [comment]
Hey @deboraazevedo, I recently discovered that Brazil have an _Anti-Racism Manifesto_. When you have time, can you please send it to me ? Please don't worry about translating it first.Thanks !

**Comment by Marie-L** [comment]
Also, @deboraazevedo can you please let me know which Brazilian 'city' chapters have signed the manifesto ? Thanks !

**Comment by Marie-L** [comment]
@deboraazevedo please don't worry, I've got it. [Brazil Anti Racism Manifesto](https://github.com/pyladies-brazil/manifesto) thanks @cecivieira !

**Comment by deboraazevedo** [comment]
ok @Marie-L thank you @cecivieira for doing this!

**Comment by BethanyG** [comment]
@MmeMarieLouise  -- Since there has been no movement on this since 2021, I am going to close it for now.  We can reopen or re-create once the work starts again.
