### ISSUE TITLE
Communication plan for Aug 15 2019 email

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#15]
# Overview

Communication plan for August 15 2019 email in #9 !

### Scope of Work

- [X] Write and send a tweet - see [here](https://twitter.com/pyladies/status/1162061210965204994?s=20)
- [x] Update in Google groups - Pyladies [here](https://groups.google.com/forum/#!category-topic/pyladies/Z4xnFLWTlNo) and PyLadies Regional Organizers [here](https://groups.google.com/forum/#!topic/pyladies-group-organizers/sI628w6vGD0)
- [x] Update in Slack see [here](https://pyladies.slack.com/archives/C03HT05KF/p1565876469123500)
- [x] Write a PyLadies Blog Post and update the PyLadies contact info see [here](https://www.pyladies.com/blog/Important-PyLadies-Update/important-pyladies-update/) and [here](https://www.pyladies.com/about)

**Comment by Mariatta** [comment]
Emails have been sent.

**Comment by lorenanicole** [comment]
And all communication has been sent!
