### ISSUE TITLE
What time should the global interim team meet?

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#16]
# Overview

Currently the team is meeting at 10:00am PDT / 12:00pm CDT every second Weds of the month. Does this time work for everyone? 

### Questions

- What times are better for a global group?
- Do we need to change?

**Comment by trallard** [comment]
9-11 PDT is generally fine for me it falls at the end of my day (as long as I am not travelling)

**Comment by jackiekazil** [comment]
This usually works for me... hoping to catch the next one. (I lost track of a few meetings with the norms change.)

**Comment by lorenanicole** [comment]
Cool there's a meeting tomorrow at 10:00am PDT. Please see the Slack future-of-us channel as @Mariatta has setup a bot that does notification.

**Comment by Mariatta** [comment]
I think alternating meeting time is great. I'm good with the two options: 10 AM PDT and 6 PM PDT.

I would like to hear from those in other timezones like Europe/Africa/Asia if they have a better timing in mind.

**Comment by treasurechristain** [comment]
> I think alternating meeting time is great. I'm good with the two options: 10 AM PDT and 6 PM PDT.
> 
> I would like to hear from those in other timezones like Europe/Africa/Asia/Australia if they have a better timing in mind.

For me I think 5pm pdt won't be cool for we in Africa because that time is actually 00:00am for we in Africa(Nigeria🇳🇬).

I suggest we should swap the  timing between 1pm pdt or 8am pdt

**Comment by lorenanicole** [comment]
@treasurechristain ah yes, it's always going to be hard to have times every month that work for everyone.

With 10:00am PDT that's 6:00pm AST so this will work well for you. On the months we do 6:00pm PDT (which is 2:30am AST - http://www.timebie.com/timezone/pacificdaylightnigeria.php) it's more than fine to not attend! We always take notes and will post them.

**Comment by georgically** [comment]
> I think alternating meeting time is great. I'm good with the two options: 10 AM PDT and 6 PM PDT.
> 
> I would like to hear from those in other timezones like Europe/Africa/Asia/Australia if they have a better timing in mind.

6:00 to 10:00pm PDT or 7:00-9:00am PDT will be convenient for my side in Bangkok

**Comment by deboraazevedo** [comment]
10:00am PDT is working for me because it's 3pm BRT and I'm not currently working at this time of the day

**Comment by lorenanicole** [comment]
Sounds like we are reaching some quorum on this issue. For that, we'll close but anyone can reopen that is in the Pyladies Global Team GitHub group (if you aren't in it ping me) should we need to review this again.
