### ISSUE TITLE
Review Aug 15 2019 Chapter Surveys

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#25]
# Overview

Review the #9 emailed surveys including:

- Create a new master list of active chapters
- Capture themes from organizers survey
- Add to language for #24 

### Deliverables

- Some type of data analysis report on the chapter surve
- Add @trallard to the PyLadies drive with the info (@lorenanicole) and get @trallard a PyLadies email

### Questions

Who has bandwidth over the next month to work on this: @willingc @jackiekazil @elainewong @trallard ?

**Comment by trallard** [comment]
I have the bandwidth for the data analysis. As soon as I get access to the data I can start working on it @lorenanicole

**Comment by lorenanicole** [comment]
@trallard I emailed you info including your new Pyladies email account! That should get you access to everything. Please let me know if I need to resend anything.

**Comment by lorenanicole** [comment]
Some initial stats from the chapter leaders survey:

Num Responses | Num Chapter  | Relevant links | 
| --| --| --|
| 66 | 65 | #24 |

**Comment by lorenanicole** [comment]
@trallard here's a PR starting to work on this ... https://github.com/pyladies/global-organizing/pull/31 ... can you review?
