### ISSUE TITLE
PyLadies Code of Conduct - Should we update our policy to the PSF policy?

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#30]
# Overview

The Python Software Foundation, which provides PyLadies it's nonprofit status, recently update their Code of Conduct as well as their enforcement policy. This issue will capture discussion around if / how the PyLadies org should update our policy to include the PSF CoC policy better.

## Scope of work

- [ ] Read [PSF Code of Conduct policy](https://www.python.org/psf/conduct/)
- [ ] Read [PSF Code of Conduct Enforcement policy](https://www.python.org/psf/conduct/enforcement)
- [ ] Propose language for modifying our CoC *OR* reject adopting PSF CoC into PyLadies CoC
- [ ] Develop documentation for PyLadies CoC enforcement policy

## Questions

- Is there anything we wish to adopt from the PSF CoC?
- What is the PyLadies enforcement policy? Let's create documentation around this.

**Comment by trallard** [comment]
Some discussions we had around this at the last global Pyladies was:

- Adopt the PSF Code of Conduct but allow the agency to the chapters to decide on additions or amendments to tackle specific challenges of their particular chapters.
- Also, allow each chapter to decide on how to respond to code of conduct incidents at their own events, but having a PyLadies global Code of Conduct team and process to escalate issues when needed.

These are the approaches currently followed by the PSF and regional conferences as well as The carpentries.

**Comment by lorenanicole** [comment]
For context this is The Carpentries - https://carpentries.org/

**Comment by willingc** [comment]
I think a consistent CoC with the PSF is a good starting point.

**Comment by BethanyG** [comment]
This was done in 2021, I think.  Closing.
