### ISSUE TITLE
RFC: PyLadies Projects

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#33]
# PyLadies Projects

### Overview

The Global Interim PyLadies group closed the RFC for proposing a PyLadies Global Governance Model, including the creation of project teams - #11 - on September 15, 2019 and we will be moving to the next stage of the process.

In this next stage, below we have proposed initial projects that PyLadies Global will officially support. We will outline each proposed project as well as how community members can become involved in the project(s).

*This RFC will close on December 4, 2019 23:59:59 Anywhere on Earth.*

Please circulate this with any and all PyLadies members.

### Qualifications

Any self-identifying PyLadies member can participate as a contributing member. Additionally each project will require a project lead or project leads. Any project member can self-nominate or nominate another person to be a project lead. If nominating another to be a project lead, the individual must be a self-identifying PyLadies member and their consent will be required (e.g. an email sent to the person and they consent to participate). 

Membership as a PyLadies member, therefore, will rely on self-identification. 

Additional requirements to consider:
- Basic communication in English or ability to alternatively contribute to the project team through English (e.g. a local volunteer can help include updates in English representing volunteers from a geographic region)
- Reasonably responsive on email, GitHub, and Slack 

### How to Propose a Project

The beneath are topic project proposals, but moving forward new project proposals should be opened as a GitHub issue on the main global-organizing repo: https://github.com/pyladies/global-organizing/issues/new/choose with the project proposal template (see below). The project proposal should include: project name, what problems the project will work, who will be the initial project lead(s), information on how the project team will work.

![image](https://user-images.githubusercontent.com/4573607/67128489-35d3a600-f1d2-11e9-9894-ddd01815dc6a.png)

You can look at this [example for the Code of Conduct project proposal](https://github.com/pyladies/global-organizing/issues/34).

### Project Proposals

This section enumerates initial proposals for project topics. 

#### Code of Conduct

As an organization situated beneath the Python Software Foundation, PyLadies is subject to the PSF Code of Conduct. Additionally as a global organization we should offer a place for PyLadies to handle our own incident reports as well as have discussion related to any Code of Conduct considerations. Most importantly, though, this project team would offer support to our chapter organizers in training, knowledge acquisition, and more. 

#### Communication

PyLadies has had a blog on pyladies.com that has gone dormant. We would like to revitalize our communication and outreach efforts including working on the blog, managing our social media presence, and building up our PyLadies Slack. This project team would handle strategy, content creation, and as well management of communication. 

#### Finance

While there is a Python Software Foundation Grants program, PyLadies itself has a central set of finances available that could be better used to support our global chapters. Examples may include expanding financial aid at global Python conferences, having finance options available for chapters to obtain t-shirts, stickers, or other swag. Lastly, this group could help determine what to invest finance in and consider ways to help fundraise on behalf of PyLadies. 

#### PyLadies at PyCon(s)

Looking at PyCon US as an example, PyLadies has a presence at PyCon US with programming including the PyLadies auction, PyLadies lunch, and the PyLadies booth. This project team can help build out similar programming at other global Python conferences as well as offer input on the size of PyLadies financial aid benefits for global Python conferences. Examples of work to be done include developing reusable assets, documentation on what PyLadies at PyCon programming may mean, and performing outreach to get a team that can help setup and staff events.

#### Resources

Many new PyLadies chapters ask common questions such as “what is your chapter doing this month” and may ask for example lesson(s) or tutorial(s) to run in their chapter. This project team will help curate chapter specific resources and manage those resources on https://github.com/pyladies/pyladies-chapter-resources. Additionally, helping chapters with onboarding would fall under this project team’s purview.

#### Technology

Maintaining PyLadies technology will be scoped to helping maintain pyladies.com, helping chapters with setting up their websites under the pyladies.com domain, and anything else that may be needed for the PyLadies chapters technology needs. 

### Questions

- What other project teams would you like to see?
- Do any of the above projects seem redundant or should be scoped differently?

**Comment by pyladiesowerri** [comment]
I suggest that we should look into the global scope and find out one of the challenges we are facing, then develop a system that will solve that particular issue.

for instance, in Nigeria universities, most lecturers do harass their female students sexually because of mark/score. 
if we can come up with a project where this students can report any abuse from the lecturers anonymously, i guess, this will reduce abuses from those lecturers involved.

Thank You.
Amadikwa Joy N.
PyLadies Owerri Chapter

**Comment by pyladiesowerri** [comment]
We find it difficult to organize meetups in our local chapters due to venue(lack of fund to pay for venue).
So, i suggest, if we can help this local chapters to pay for venues yearly. At least the burden on their shoulders on getting things done will reduce.

**Comment by pyladiesowerri** [comment]
I also suggest that, the pyladies body should once in while organize organizers event( an event that will bring organizers together under one roof) so the can discuss on the way forward, base on how we can make our local chapter improve/progress. Hearing an organizer in another community discuss or state her success story, the other organizers will be motivated and be able to organize her community the best way. It can be an all paid trip.
with this, we will be able to work together in other to achieve one goal.

Thank You,
Amadikwa Joy N
PyLadies Owerri Chapter

**Comment by Mariatta** [comment]
The organizers' meeting once a year sounds great.

**Comment by lorenanicole** [comment]
@pyladiesowerri are you advising a global meeting of all organizers? We can definitely plan a **remote** summit I think. 

As for the regional issues we confront, that is definitely the intent behind these focused project teams.

Here's an example where you can weigh in:

- For Code of Conduct issues as it relates to organizing in Nigeria, is there anything in the scope of the project team here you would like to add https://github.com/pyladies/global-organizing/issues/34?

**Comment by pyladiesowerri** [comment]
Remote meeting sounds cool. 
I think we can be doing the remote meeting like ones every 2-3months, but one of the issue we in Nigeria will be facing will be on data bundle and network, because, data bundle is very costly and we have post network, thereby reducing our usage of internet. 

Also the on-site meeting is also necessary, so we get to discuss facially. Because I believe that, lots of ideas flow well when you are discussing with someone directly.

**Comment by lorenanicole** [comment]
@pyladiesowerri for PyLadies Projects this is the idea:

- PyLadies project teams determine how they work and how they will meet
- On some regular schedule the PyLadies project teams report to the PyLadies Global Council

You can reference #11 for the proposed PyLadies organization chart. 

Does that help?

**Comment by melostbr** [comment]
Sorry for the confusion, but should the _**Project Proposal**_ be used for when I want to create a new chapter in my city or does it continues to be as in http://kit.pyladies.com/en/latest/prospective/index.html?

**Comment by lorenanicole** [comment]
@melostbr thank you for asking! This is for PyLadies projects, not PyLadies chapters. You can see here what projects are:

![image](https://user-images.githubusercontent.com/4573607/67421092-2f647600-f5a6-11e9-8995-7e4ee13b0b18.png)

Issue: #11
PyLadies Global Organization Structure: https://user-images.githubusercontent.com/4573607/62094877-3fd5b080-b244-11e9-822a-efce65767f6b.png

**Comment by lorenanicole** [comment]
@willingc yes! I think we need to think about how to implement that but a first pass is to soften language requirement here. Thank you for the feedback. 🙇‍♀

**Comment by trallard** [comment]
That is a great point @willingc I agree with replacing the proficiency for basic English usage.
Somethings we can do to help ease the language barrier:
- Record the meetings and make them public with the transcript 
- Use close captioning (at the moment  we use Hangouts and they have CC) for meetings
- Evaluate localisation for important resources

**Comment by lorenanicole** [comment]
@trallard that's great! Or, perhaps as a minimum requirement, require that project teams take meeting minutes and provide them. We can then find a software to use to translate ... and luckily there's a translations workgroup we can get some input from!

**Comment by thursdayb** [comment]
Is it worth considering a wider 'Inclusion' project beyond just a Code of Conduct project?

**Comment by lorenanicole** [comment]
@thursdayb I think that sounds like an awesome idea. If you want to propose a project ... go for it!

**Comment by treasurechristain** [comment]
Base on some questions new chapters ask about things to do or way forward of their chapter. I think is a good thing for us to map out projects for each region or each region should come up with one or two projects that all the chapters within that region will focus on for the year. Then the chapters will work towards that direction. 

For instance, we have about 10 or more Pyladies chapters in Nigeria, so if all the chapters within Nigeria will come together and discuss on the projects or areas to consider for a year, I think that will be fruitful and beneficial to everyone, than everyone moving on different directions.

That's my thought. 

Thanks... 
Pyladiesimo...

**Comment by lorenanicole** [comment]
@treasurechristain I'm a little worried about us telling chapters what they should work on. This is fundamentally against the nature of what Pyladies is, we have always been a decentralized set of chapters. The Global Council is specifically about taking on items that require a global team to work on them, such as fundraising, chapter creation / administration / logistics.

Perhaps instead we can have a project specifically called "PyLadies Africa" and then there's a regional team that works on coordinating the chapters within Africa? An example may be to mirror what PyLadies Brasil has done -- and very successfully done. Ask @deboraazevedo for more info!

**Comment by treasurechristain** [comment]
OK, now I get it. Will love to know more on what Pyladies Brazil did.

**Comment by trallard** [comment]
Maybe by having enough regional representation in the governing body we can have somewhat of a "regional" lead/steward/coordinator? Something that scales / adapts what Brazil Pyladies did? It would also help bring their voices back and identify ways to better support each region based on their specific barriers or goals

**Comment by lorenanicole** [comment]
@trallard my only concern again about mandating too much up front structure is prematurely optimizing before knowing what will work. 

If we, say, encourage PyLadies Project teams for each continent that may be minimal enough to start. But we need community members to step up and lead. I think offering this as a suggestion to the initial Council therefore is a good place to start. So maybe we can start an issue tracker with open questions we want the initial Council to consider.

**Comment by trallard** [comment]
Yup I am concerned about that too. But I also think it would be good to have mechanisms that would allow the council to identify regional challenges an opportunities accordingly.

Though balance to find among representation, freedom of activities and council boundaries

**Comment by lorenanicole** [comment]
@trallard if you want to kickstart that issue I’d be thankful 🙃🙃🙃💖

**Comment by deboraazevedo** [comment]
Well, here in Brazil that's what we do: we have about 30 active chapters around the country (if I'm not mistaken), which are completely independent from one another. Once a year, we have a general meeting that happens at Python Brazil, which is something like our PyCon here. In Brazil, we have a national PyLadies conference (the first one was last year, we had our second this year, and we're planning for the next one!) and also we do a crowdfunding for women to attend Python Brazil, which makes the conference more diverse and also helps us A LOT during this annual meeting we have, because we can bring together women from all over the country and there are always different points of view that help us tackle very meaningful problems and situations we have, and how we can help PyLadies, lboth locally and nationally, to face and do something about our problems.

**Comment by lorenanicole** [comment]
The regional organization of PyLadies sounds really interesting to me. However again I think this should be someone proposing some type of regional PyLadies project team then to coordinate that effort. Without regional volunteers to own this work we will find ourselves again in a situation where there is inaction.

**Comment by lorenanicole** [comment]
Closing this issue with this PR now that the RFC period has closed: https://github.com/pyladies/global-organizing/pull/48.
