### ISSUE TITLE
PyLadies Project Proposal: Code of Conduct Project Team

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#34]
# Project Proposal

## Is this a new project?

- [X] Yes
- [ ] No

## What is the name and focus area of this project?

The purpose of this project team is to foster a diverse and inclusive PyLadies community by enforcing our Code of Conduct, as well as advise on issues of interest as it relates to the Code of Conduct. This goal will be achieved by: advising, reviewing, and as needed updating the PyLadies Code of Conduct; assist in training and processes to help PyLadies organizers implement and enforce the Code of Conduct; establish standards for how the Code of Conduct will be uniformly applied in all PyLadies spaces (e.g. chapters, PyLadies events at PyCon US, PyLadies Slack). 

## Who will be the project lead(s)?

Project Lead(s): @lorenanicole 

While @lorenanicole is proposing this project, there should be another project lead or two.

## Who will be the team member(s)?

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Lorena Mesa | @lorenanicole | PyLadies Chicago | Co-Lead |
| Tania Allard | @trallard | PyLadies Northwestern UK | Co-Lead |

## What are the initial unit(s) of work the project will target?

* Advising, reviewing, and as needed updating the PyLadies Code of Conduct
* Assist in training and processes to help PyLadies organizers implement and enforce the Code of Conduct
* Establish standards for how the Code of Conduct will be uniformly applied in all PyLadies spaces (e.g. chapters, PyLadies events at PyCon US, PyLadies Slack) 

## How will the project team work?

Due to the sensitive nature of this work, the PyLadies Code of Conduct project team should work in a manner that is private to only the project team for ongoing work with a separate public PyLadies repo available for any resources created. 

Proposal:
* Email alias like conduct@pyladies.com to contact the project team
* Private invite only Slack channel in PyLadies for project team
* Public repo for any assets / resources created e.g.  pyladies/code-of-conduct

## Is there anything else relevant to the scope of this project?

This group will always be evolving it's focus. However project members should represent the geographic richness of PyLadies as well as have monthly reports to the PyLadies Global Council.

cc/ @pyladies/core

**Comment by pyladiesowerri** [comment]
I suggest that we should come up with a target of what our yearly calendar will be for next year. For instance, saying that each chapter will work with this target for the year, at least with that, we will be able to achieve something tangible; instead of a situation where everyone is just organizing hackathon without a tangible return. 

We should also, have a date in the calendar called PyLadies day, on that day every chapter will organize a hackathon for the ladies. It will be superb. With this, it will help to publicize PyLadies within the ecosystem among different countries.

**Comment by trallard** [comment]
I would be happy to co-lead this working group

**Comment by thursdayb** [comment]
I'm happy to be on the team, though I'd rather not be a team lead.

**Comment by thursdayb** [comment]
Is it worth exploring widening this project to cover inclusion as a whole? For instance, accessibility  seem like they'd fit with CoCs as a part of a larger 'Inclusion' project.

**Comment by trallard** [comment]
Oh yes!!! I love this idea I would be more than happy to write the scope for the project @thursdayb! And it would be awesome if you could add some ideas too

**Comment by thursdayb** [comment]
@trallard I'm happy to add ideas!

**Comment by wnjnz** [comment]
I think the proposal items all make sense and I would like to assist in making them happen.
 
For instance, I can contribute with assisting training and establishing processes to help PyLadies Organizers meaningfully implement and enforce CoC, starting with my local Houston chapter.

**Comment by lorenanicole** [comment]
Yesssssssssssss @wnjnz would you want to join as a workgroup member?

**Comment by wnjnz** [comment]
🤚 yes!
