### ISSUE TITLE
PyLadies Project Proposal: Technology and Infrastructure team

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-organizing#35]
# Project Proposal

## Is this a new project?

- [x] Yes
- [ ] No

## What is the name and focus area of this project?
Administer and maintain PyLadies tech and infrastructure.

## Who will be the project lead(s)?

Project lead(s): @Mariatta 

## Who will be the team member(s)?

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Mariatta | @Mariatta  | PyLadies Vancouver | Co-Lead |
| Bethany G | @BethanyG   | PyLadies Oakland | Co-Lead |
| Tania Allard | @trallard  | PyLadies Northwestern UK | Co-Lead |
| Lorena Mesa* | @lorenanicole | PyLadies Chicago | Member |
| Carol Willing | @willingc   | PyLadies Core | Member |
| Jackie Kazil | @jackiekazil   | PyLadies DC | Member |
| Flávia Cardoso | @fcardoso0917  | PyLadies Uruguay | Member |
Amadikwa Joy N | @treasurechristain | Pyladies IMO | Member |
* @lorenanicole is a PyLadies admin that can help support the co-leads as needed.

## What are the initial unit(s) of work the project will target?

- PyLadies.com maintenance and subdomain
- Improvements to  pyladies.com website, such as implementing new meetup API (https://github.com/pyladies/pyladies/issues/405) and implement new PyLadies map (https://github.com/pyladies/pyladies/issues/412)
- PyLadies slack bots
- review pull requests to pyladies.com

## How will the project team work?

Contributions are welcome and open to anyone.
New GitHub repos can be created as necessary. For the most part, we should be able to use the existing repos at https://github.com/pyladies/pyladies/ and https://github.com/pyladies/global-organizing.

If desired, we can create the #pyladies-tech channel in Slack.

## Is there anything else relevant to the scope of this project?

The tech team will not necessarily be responsible for the "content" of the website. Perhaps that can be owned by the communications team.

cc/ @pyladies/core

**Comment by lorenanicole** [comment]
Love this proposal @Mariatta ! Would definitely love to join in as well.

Questions:

- Do we imagine that things like getting passwords reset for emails, creating pyladies emails falls into this team?
- For automation tasks, such as PyLadies Slack bots, would we need a budget for this project team?

**Comment by trallard** [comment]
I am happy to join this team, mainly as I have been interested in creating an interactive dashboard to keep track of the chapters and the events. 

As per the content of the site / blog I do agree this should be owned by the communications team.

**Comment by Mariatta** [comment]
> For automation tasks, such as PyLadies Slack bots, would we need a budget for this project team?

I think we will need budget for hosting the webservice like Heroku or something, and I'd like for us to have our own Zapier account, instead of using mine.

**Comment by Mariatta** [comment]
> Do we imagine that things like getting passwords reset for emails, creating pyladies emails falls into this team?

Hmm not sure... Feels more "administrative" but perhaps initially the tech&infra team can look into it.

**Comment by lorenanicole** [comment]
Makes sense! I think that makes sense from where I sit. I guess just any type of automation should live in this team? And this team can approve/review?

**Comment by jackiekazil** [comment]
I am interested in this as well.

**Comment by willingc** [comment]
I am happy to help review PRs and assist developers.

**Comment by BethanyG** [comment]
I'm happy to help in any way I can.  😄

**Comment by fcardoso0917** [comment]
I would like to help with what I can :dancing_women:

**Comment by lorenanicole** [comment]
@BethanyG @willingc @jackiekazil I added you all to the member list above. Please indicate if that is incorrect, we are still looking for a co-lead here to help since this would be a more active Project I think.

@fcardoso0917 could you confirm your details? Perhaps adding this in your comment:

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Flávia Cardoso | @fcardoso0917   | (What's your chapter? If none local, just add @pyladies) | (What level? Member?) |

**Comment by fcardoso0917** [comment]
I don't understand the team role. I am an organizer of the local group
(PyLadies Uruguay). Am I a member?

Em Ter, 10 de dez de 2019 4:49 PM, Lorena Mesa <notifications@github.com>
escreveu:

**Comment by lorenanicole** [comment]
@fcardoso0917 ah I see it looks like you manage this chapter [here](https://www.meetup.com/Grupo-de-Meetup-en-Montevideo-de-Python/). It is worth noting that PyLadies chapters are scoped to cities  rather than countries, since if another request comes in for Uruguay we want to ensure there is no naming confusion. We should follow up in Slack.

**Comment by treasurechristain** [comment]
I will love to be part of the team

**Comment by treasurechristain** [comment]
Amadikwa Joy N
@treasurechristain 
@Pyladiesimo
Member

**Comment by trallard** [comment]
If still looking for co-lead write me in

**Comment by lorenanicole** [comment]
@Mariatta do you want another co-lead?

@trallard the big thing here will be if you are co-leading this group that there's a time sensitivity to managing this work (e.g. being able to review and create subdomains within a week of a request coming in);

**Comment by BethanyG** [comment]
@treasurechristain  -  Edited proposal to add you as team member.

**Comment by Mariatta** [comment]
I'm good with having @trallard as co-lead thanks!

**Comment by trallard** [comment]
I can make sure to block a regular hour(s) each week to deal with teams tasks :)

**Comment by lorenanicole** [comment]
@Mariatta im happy to be added to a rotating schedule for helping with these admin sub domains etc alongside you @trallard and @BethanyG. @econchick we will need @trallard to be setup with cloud flare too 🥰.
