### ISSUE TITLE
PyLadies Project Proposal: Finance team

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-organizing#36]
# Project Proposal

## Is this a new project?

- [x] Yes
- [ ] No

## What is the name and focus area of this project?

A team to handle financing of global pyladies and help local chapter with financial needs

## Who will be the project lead(s)?

Co-Lead: @lorenanicole 

## Who will be the team member(s)?

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| -- |
| Lorena Mesa | @lorenanicole | PyLadies Chicago | Co-Lead |

## What are the initial unit(s) of work the project will target?

It would be great to have a central team to manage and handle financials for Global and local pyladies.
Some financial-related problems that have arised in the past:
- a chapter wants to print sticker/t-shirt, how can they pay for this? 
- pyladies member got invited to speak at a conference, but financial aid was inadequate, how can we support them?
- people want to buy pyladies merchandise, how can we set up the store and where does the money go to
- sometimes we want to charge ticket to local chapter's meetup, how can we handle the payment?
- Mariatta would like a Zapier account for PyLadies, how can we pay for it?
- etc 

## How will the project team work?

tbd

## Is there anything else relevant to the scope of this project?

cc/ @pyladies/core

**Comment by lorenanicole** [comment]
I'm willing to put my name forward as a project lead on this provided we have other team members. I think having 2 to 3 leads on this makes most sense. 

Questions:

- Should we have a regional team requirement (e.g. a pylady per regional area like pylady per continent)?

**Comment by Mariatta** [comment]
Thanks for stepping up @lorenanicole!

Having representatives of diverse pyladies community in the team would be great.

**Comment by willingc** [comment]
It would be great to have a regional representative if possible.
