### ISSUE TITLE
PyLadies Project Proposal: A Python for Data Science Open Source Workshop!

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#37]
# Project Proposal

## Is this a new project?

- [X] Yes
- [ ] No

## What is the name and focus area of this project?

*Overview*

Many of us know Django Girls, a highly successful organization that has created an open source workshop to help people (but written with marginalized genders in mind) get started with Django and publish their first blog to the internet.

Python, however, has many use cases. Notable of which is Python's use in scientific computing and data science / machine learning.

As the [2018 JetBrains Python developer survey](https://www.jetbrains.com/research/python-developers-survey-2018/) found, some 58% or primary Python users use Python for data analysis and some 38% primary users polled for machine learning:

![image](https://user-images.githubusercontent.com/4573607/67421730-7bfc8100-f5a7-11e9-9e4b-ad9b8bcbcdaa.png)

What could PyLadies create to help educate folks on how to bootstrap a data science pipeline? 

*Questions* 

* What should be the learning objective for such a workshop?
* Where should this project live?

*Project Proposal: Python for Data Science Open Source Workshop!*

Develop an open source Python workshop teaching users how to build a data science pipeline, build a model, and surface behind an API wrapper.  Resources for the workshop include: lesson plan, organizer's handbook, project repository for improvements. The workshop will aim to be translated into more languages than English. 

## Who will be the project lead(s)?

@lorenanicole 

## Who will be the team member(s)?

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Lorena Mesa | @lorenanicole | PyLadies Chicago | Co-Lead |

## What are the initial unit(s) of work the project will target?

* Write the 1-2 sentence education statement of what the workshop will teach
* Investigate technology used for workshop
* Determine where the project will live
* Offer translation of workshop
* Ship an open source workshop on whatever website/code repo website project team determines

## How will the project team work?

This will be a short-term to medium-term project. Once the initial version is shipped, we will either disband this project team or move it into another one ( e.g. chapter resources ).

## Is there anything else relevant to the scope of this project?

Anyone with any Python experience is welcome! 

cc/ @pyladies/core

**Comment by trallard** [comment]
I love this but would like to involve the other folks in the community that are already taking part in this (Cheuk and Sandrine) as I already agreed to work on this with them and it would make sense not to duplicate efforts.

**Comment by gise** [comment]
Hi @lorenanicole, 

I'm co-organising a Data workshop for PyLadies London with the people from PyData London. We're still fine-tuning the content, duration and date (aiming for January). If you want, we can talk after the first iteration to see if it has parallels with what you had in mind.

**Comment by lorenanicole** [comment]
@gise @trallard can you all revise this description then? This type of workshop isn't necessarily unique to PyLadies obviously. Additionally wasn't sure how to capture a project like this in the repos. Any thoughts on how to better place this in front of the community for anyone that may be interested in helping with it?

**Comment by gise** [comment]
I'll have a more clear vision myself of this can look within the next two months as we put together the material and the scope. I'll make a note to come back to this issue in January and give an update.

**Comment by willingc** [comment]
Please keep me in the loop too. Happy to help 👍

**Comment by willingc** [comment]
It would be great to develop it with some Jupyter notebooks so that we can have it be self-serve via mybinder.org.

**Comment by lorenanicole** [comment]
@trallard @gise I think what would be good even is if there's some kind of organization around this where we can track:

- Resources developed
- Solicit volunteers to proof / review 
- Solicit translations 

And other cool ways we can get this project going.

**Comment by willingc** [comment]
Perhaps use the Carpentries templating?

**Comment by trallard** [comment]
Agree @lorenanicole I think if we have a centralized resource tracking it will help with discoverability, sustainability and reusability

**Comment by Caaddss** [comment]
about the organization trails? 
Has there been a break on these trails? How can I help the project?
I would like to join the team !!!!

**Comment by leticiadasilva** [comment]
This project is amazing!!!! I want help, of course. 
How do I do? I already want to start yesterday haha

**Comment by Caaddss** [comment]
@leticiadasilva we could start translating to English our DS material, so they can give their opinion on what we already have !! what do you think?

**Comment by leticiadasilva** [comment]
@Caaddss it's great! For me, it's a good way to start.

**Comment by Caaddss** [comment]
@leticiadasilva AMAZING

@lorenanicole what do you think?

**Comment by lorenanicole** [comment]
@Caaddss / @leticiadasilva we have some colleagues in the UK who are actually working on something like this. @trallard and I attended a meeting to chat with them on it, I think it may be better to join efforts rather than divide and conquer.

**Comment by Caaddss** [comment]
@lorenanicole WOW, ok!!!

**Comment by lorenanicole** [comment]
@Caaddss while I opened this issue, I think this may not be needed right now. A group of people in the United Kingdom are doing some of this work, specifically trying to do a "Data Science for All" in a Django Girls fashion.

**Comment by Caaddss** [comment]
@lorenanicole ok

**Comment by lorenanicole** [comment]
Closing this for the time being as this may be more a campaign rather than an ongoing project team.
