### ISSUE TITLE
PyLadies Project Proposal: Chapter Administration and Logistics

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-organizing#38]
# Project Proposal

## Is this a new project?

- [x] Yes
- [ ] No

## What is the name and focus area of this project?
PyLadies Chapter administration and logistics (I don't know a better name)

Focus area:
- review, approve/reject new chapter requests
- follow up with inactive chapter, help and manage the handover
- create new chapter 
- handle password reset
- etc

## Who will be the project lead(s)?

Creating new chapter and password reset require PyLadies Admin account in GSuite. However, other activities like reviewing chapter requests and other email communication do not require an admin account. As such, Project lead(s) should be one of the PyLadies Admin account, however team members can be any self-identifying PyLadies member.

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Mariatta | @Mariatta  | PyLadies Vancouver | Co-Lead / PyLadies Admin|
| ??? | ??? | PyLadies ??? | Co-Lead |

## Who will be the team member(s)?

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Jackie Kazil | @jackiekazil | PyLadies DC | Team member | 
| Debora Azevedo | @ deboraazevedo | PyLadies Brasil/Natal | Team member |

## What are the initial unit(s) of work the project will target?

1. Come up with a guideline of how to approve/reject chapters
- do we have requirement about chapter proximities with another chapter? (i.e. if there is already a Vancouver chapter, do we allow a Burnaby chapter?)
- do we have requirement about who is running the chapter?  (i.e do we expect at least two co-organizers?)
- do we have requirement about their intent with this chapter? (i.e. do we expect they have a meetup once a year)

2. Review pending new chapter requests once a month. 

3. Review "password reset" form and assist with password reset

4. Come up with guideline regarding inactive chapters
- at what point do we consider chapter inactive? (example: if they're unreachable after X days?)
- how do we handle handover to new chapter leaders?

## How will the project team work?

There is #project-admin-logistics channel in PyLadies Slack.

Suggestion:

### New chapter review

Co-leads and members should be a member in PyLadies Slack.
Join the #feed-new-chapter channel. New chapter requests are posted there.
Review chapter requests once a month and give approval. (either asynchronously, or meeting once a month)
Co-lead/administrator can create the approved chapters.

### Password reset review

TBD

## Is there anything else relevant to the scope of this project?

cc/ @pyladies/core

**Comment by jackiekazil** [comment]
I think I could be a good help with this. I am doing some of this with Pyladies DC hand off right now.

**Comment by AbigailMesrenyameDogbe** [comment]
One way we could track the existence and continuity of a Chapter will be to ask for reports from Leads twice a year. So one for the first half and the other for the second half. Leads would give a brief of what their chapter has been up to and any problems their facing. This would also help the community in providing mentorship and making sure that all the Chapters are actually running.

**Comment by jackiekazil** [comment]
I think that is a great idea? Also one of the things that chapters don't know about often is that the PSF will pay for their meetup fees, so 2x per year is a great time to remind people of this opportunity.

**Comment by lorenanicole** [comment]
I think for password reset, we should do something like this ...

# Proposal

### Procedure
1. Fill out a form 
2. Is the form filled out:
    - Authorized admin in our chapter directory? Great. Reset it.
    - If not, reach out to find out why a different party is requesting

### Tooling
Use a Google script to automate ... there's a lot of power in Google app scripts I found

**Comment by lorenanicole** [comment]
Should I open a GitHub repo for this project and add those on the "project team" in the issue description to this repo? Or ... is a project board enough?

**Comment by jackiekazil** [comment]
I could see a series of tooling.

**Comment by lorenanicole** [comment]
Closing this issue as this team has started with project repo: https://github.com/pyladies/project-admin-logisitics.
