### ISSUE TITLE
Monthly PyLadies Meeting Notes: July 29, 2019

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#4]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

**Initial Details**

- Previous meeting issue link: https://github.com/pyladies/global-organizing/issues/1
- Current meeting attendees: @Mariatta @elainewong @willingc @lorenanicole 

**Meeting Topics**

_Please add items as needed. If you add a topic please make sure to attend the meeting._

_New Business_

- [x] Each pyladies chapters have to share email password among co-organizers, but 2FA is a pain when it's tied to phone number. Is there a better way to do this? Can we use tools like 1Password and request grant from The PSF for it? (@Mariatta)
- [x] What are guidelines for starting a new PyLadies chapter? Do I approve any new incoming requests? Can men start a PyLadies chapter? (@Mariatta) 

_Old Business: Follow up items from prior meeting:_
  - [x] Review feedback on governance models https://github.com/pyladies/global-organizing/issues/3
  - [x] | Make a listing of all PyLadies chapters including which active and who the point of contact is @Mariatta @katialira 
  - [x] Research what to automate after the PyLadies registration form is filled out @Mariatta 
  - [x] Create a GitHub repo, containing resources/talks/tutorials from various meetups, with purpose that other chapters can re-use the talks/resources @lorenanicole  https://github.com/pyladies/global-organizing/issues/5
  - [x] Work on updating website, checkin with @econchick on this @RachellCalhoun

**Action Items and Assignees for Next Meeting**

| Action Item | Owner | Relevant links | 
| --| --| --|
| Communication Plan to get PyLadies chapter list | @lorenanicole @Mariatta @elainewong @willingc | #9 |
| Website Update / Pruning resources | @willingc @lorenanicole @elainewong @Mariatta | #6 |
| Write-up public RFC Issue for PyLadies Global Model | @lorenanicole | https://github.com/pyladies/global-organizing/issues/11 |
| Post July 29 minutes | @lorenanicole | https://github.com/pyladies/global-organizing/blob/master/notes/2019/29_07_2019.md |

**Comment by lorenanicole** [comment]
@econchick for the PyLadies Slack admins can you please add the following as Slack admins:
- @lorenanicole 
- @willingc 
- @elainewong 

As per the Google groups, we have decided we want to archive these groups. Our plan is to have an email sent to all chapter emails and also share in Google groups and Slack updates on many things including this move to using only PyLadies Slack. Our goal is to email, post, and Slack all these communications on Aug 15th. The goal is to close the Google group on September 15 2019. Can you add me and @Mariatta as admins for the Google groups then so we can handle this?

**Comment by Mariatta** [comment]
Since all items have been discussed and addressed, I'm closing this.
Any leftover items can be discussed in August 14's meeting.
Thanks.
