### ISSUE TITLE
PyLadies Project Proposal: Communications

### ISSUE THREAD

**Issue by AbigailMesrenyameDogbe** [pyladies/global-organizing#42]
# Project Proposal

## Is this a new project?

- [x] Yes
- [ ] No

## What is the name and focus area of this project?

A team to handle the Global PyLadies Communication and Engagement work.

## Who will be the project lead(s)?

@AbigailMesrenyameDogbe 

## Who will be the team member(s)?
 
Name | GitHub Handle | PyLadies Chapter | Team Role
-- | -- | -- | --
Abigail Dogbe | @AbigailMesrenyameDogbe  | PyLadies Ghana | Co-Lead
Lorena Mesa | @lorenanicole  | PyLadies Chicago | Member
Caroline Dantas | @caaddss | PyLadies São Paulo | Member
Emily Spahn | @eyspahn | PyLadies Seattle | Member
Marie-Louise | @Marie-L | PyLadies London | Member
Bethany Garcia | @BethanyG | PyLadies Oakland | Member

## What are the initial unit(s) of work the project will target?

- The PyLadies blog

- Managing Slack community 

- Newsletter

- Communicating upcoming events of the Global PyLadies Community

- Keeping in touch with Chapter Leads to ensure continuity

## How will the project team work?

Communication will be done through slack on this channel [#project-communication](https://app.slack.com/client/T03HT05JZ/GQVTKTP9T). Also project work will happen on the [Project Comms repo](https://github.com/pyladies/project-communications/).

## Is there anything else relevant to the scope of this project?

cc/ @pyladies/core

**Comment by lorenanicole** [comment]
@AbigailMesrenyameDogbe what do you think about making a Slack channel called `#project-commmunication` for this group? Or whatever name you think is best, we can add it to the section here under `How will this team work`!

**Comment by Caaddss** [comment]
Hey!! Awesome!! I want to help!!!

**Comment by eyspahn** [comment]
I'm interested in helping as well! - emily / seattle

**Comment by lorenanicole** [comment]
@eyspahn and @Caaddss can you both add your names to the team member(s) name above like so:

![image](https://user-images.githubusercontent.com/4573607/69455434-0282ba80-0d2e-11ea-8874-7cd0859f9654.png)

**Comment by Caaddss** [comment]
Didnt appear this option here ><

**Comment by eyspahn** [comment]
I don't have the edit option either - maybe we need to be added as members of the group on github?

**Comment by Marie-L** [comment]
I want to help  too ! @lorenanicole the option doesn't appear for me either

**Comment by BethanyG** [comment]
@Caaddss @eyspahn @Marie-L -- I wanted to help too...and **did** have access to edit, so went ahead and added you three while I was adding myself.  Please let me know if you need me to change or update your information.

**Comment by leticiadasilva** [comment]
YAY, I would love to help. How do I do?

**Comment by lorenanicole** [comment]
Thanks @BethanyG I actually need to adjust permissions. We should keep admin to those in the work group then add a contributor bucket.

**Comment by lorenanicole** [comment]
@BethanyG I think the following folks want to work on the project team:
- @eyspahn 
- @Caaddss 
- @Marie-L 
- @leticiadasilva 

Which is fantastic! I'll start a repo on this project team.

**Comment by lorenanicole** [comment]
Repo created! Who wants to be an admin on the repo? https://github.com/pyladies/project-communications/

**Comment by Caaddss** [comment]
> Repo created! Who wants to be an admin on the repo? https://github.com/pyladies/project-communications/

me

**Comment by lorenanicole** [comment]
Closing this issue as this team has started per https://github.com/pyladies/global-organizing/issues/42#issuecomment-558789110.

**Comment by Ash-Renee** [comment]
HI i'd love to be a part of this- Ashley (SF Bay area)

**Comment by nidhikamath2102** [comment]
I want to propose an idea. Where is the best place to do that? Can someone help me here?

**Comment by BethanyG** [comment]
Please open a new issue @nidhikamath2102 -- this one is closed, and commenting on it only spams those who have commented on it.

**Comment by reshamas** [comment]
> I want to propose an idea. Where is the best place to do that? Can someone help me here?

@nidhikamath2102 Thanks for reaching out. For suggestions or ideas, you can open up a new issue here:
https://github.com/pyladies/global-organizing/issues
