### ISSUE TITLE
PyLadies Global Council Timeline

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#46]
# Overview

This issue outlines the proposed timeline for the PyLadies Global Council selection process. 

### History

From the Python Software Foundation (PSF) Board of Directors meeting in Nov 2019, the PSF advised that the selection for the PyLadies Global Council should coincide with the PSF Board of Directors election. The 2019 timeline can be found [here](https://www.python.org/nominations/elections/).

### 2020 Election

_We'll be syncing with a similar setup as the PSF Board of Director 2020 elections._

**Who can vote:** Any self-identifying PyLadies member, that is registered.

```
    Open call for Council Member Nominations: Aug 6, 2020 AoE
    Council Member Nomination cut-off: Aug 31, 2020 AoE 

    Voter application cut-off date: Aug 31, 2020 AoE 

    Voting start date: Sept 7, 2020 AoE 
    Voting end date: Sept 18, 2020 AoE
```

**Comment by gise** [comment]
We have members that are going to sit in the council for 1 year and others that will sit for 2 years. So my question is in this first vote, how will we make clear to voters who is gonna get a 2 year seat and who is going to get a 1 year seat? Is it different nominations? Can someone be nominated for both types of seats?

**Comment by jackiekazil** [comment]
There are multiple ways that I have see this done. The way the PSF did this was by # of votes -- which equates with popularity. I think that is somewhat troubled, because that will lead towards Western bias. 

The other way, which I have seen and would recommend is by a lottery after the board is established.

**Comment by lorenanicole** [comment]
@gise I'm in favor of a lottery then for the 1 year vs 2 year distinction that @jackiekazil proposed. That is, after the Council members are selected/elected (if we will select or elect is the subject of #11, so please weigh in there if you prefer one or the other) we have some lottery mechanism that assigns the 1 year or 2 year length of term accordingly.

**Comment by treasurechristain** [comment]
> There are multiple ways that I have see this done. The way the PSF   @#did this was by # of votes -- which equates with popularity. I think that is somewhat troubled, because that will lead towards Western bias.
> 
> The other way, which I have seen and would recommend is by a lottery after the board is established.

Lottery? In what aspect. I mean how? Can you explain in detail please.

**Comment by gise** [comment]
Yes, I think that for the first time a lottery for the 1 year vs 2 year distinction could work. I would make that clear to people voting just in case.

**Comment by lorenanicole** [comment]
@gise + @treasurechristain here's how a lottery would work:

Right now we are unclear if all the Council members will be chosen by election (voting) or through selection (an application process), again that is issue #11 .

However in either situation we would have language such as, "The Council member applicants with the most [votes/selected] will have a seat on the Council. The length of the term will be dictated by a lottery, randomly selecting from the Council members who has a 1 year term and who has a 2 year term".

For example if we were voting for all 9 seats, the individuals with the most votes for the top 9 will have seats on the Council. But a secondary lottery (e.g. a randomized selection think `Python` using `random`) will assign who has a 1 year term vs a 2 year term.

**Comment by lorenanicole** [comment]
The timeline has been moved back to August due to us having to adjust due to PyLadies Global Interim needing more time to prep.

**Comment by sleepypioneer** [comment]
similar to the other issues relating to the global council, @lorenanicole could this issue be closed as it appears to have been moved to Done on the project board? Perhaps however there is a reason to keep the issue open?
