### ISSUE TITLE
Add a Pyladies Projects Workflow

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#49]
# Overview

We have moved the #33 into the global organizing repo as seen here: https://github.com/pyladies/global-organizing/blob/master/process/pyladies-projects-overview.md.

Please add a "So you've started a project team, now what" section documenting the projects workflow including information on:

- Document how members can join 
- Onboarding new members
- How is the group going to communicate
- What is the basic workflow for contributions to the group
- How will the group manage the issues / units of work

**Comment by BethanyG** [comment]
In pull https://github.com/pyladies/global-organizing/pull/51

**Comment by BethanyG** [comment]
Closing as completed and merged with #51 .  Can re-open as needed.
