### ISSUE TITLE
PyLadies Global Council Election 2020

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#58]
# PyLadies Global Council Election 2020

PyLadies Organizers have voted #50 to select the inaugural PyLadies Global Council through a blended process: public election and nominations. The proposed timeline #46 has the entire election happening in April-ish 2020, specifically with the desire to sync the PyLadies election with the Python Software Foundation Board of Directions Election (that date is soon to be set).

## Scope

There are several questions to be discussed and settled below are a list related to each part of the election.

*Election Details*
The initial Council will have 9 seats, 5 will be selected through public election 4 through nomination. The members selected by nomination will hold a 2 year seat, whereas the members selected by election will hold a 1 year seat.

*Public Election*
* Should voting will be open to any registered PyLadies member?
* What happens if there are ties?
* What tech should be used for voting?

Led by: @lorenanicole

*Nomination Selection*
The nomination review will be conducted by the working Global interim group. 

* What should be the criteria for reviewing applicants?
* What should the application entail?

Led by: @whykay, [TODO: ADD MORE NAMES]

*Outreach Strategy*
The Project Comms team will be assisting in developing the comms strategy. See: https://github.com/pyladies/project-communications/issues/24.

Led by: [TODO: ADD MORE NAMES]

*Translation*
* What language(s) should we translate into?

Led by: @elainewong @deboraazevedo 

## Deliverables

- Tracker issue for public election: https://github.com/pyladies/global-organizing/issues/59
- Open tracker issue for nomination selection
- Open tracker issue for outreach 
- Open tracker issue for translation

/cc @pyladies/pyladies-global-admin @pyladies/pyladies-global-contributors

**Comment by Mariatta** [comment]
> voting will be open to any registered PyLadies member

How does one became registered as a PyLadies member? (I assume the will be a form). Does membership means they must be belonging to a chapter? (local/remote)

Do we need to set a deadline, e.g must be registered before MMM, DD, YYYY in order to be eligible to receive the voting ballot?

> What tech should be used for voting?

The PSF uses Helios voting system, that seems to work and familiar to PSF members. Perhaps we should just use the same.

> What language(s) should we translate into?

What are being translated? Like nominees bios? Or nomination criteria?

**Comment by lorenanicole** [comment]
@Mariatta can we move your comment to the relevant issues? My intent is to use this as a master checklist for all the components. But happy to adjust as you see fit!

**Comment by Mariatta** [comment]
Sure, I've moved the questions to #59. Not sure where to ask question about "what are the things to be translated"..

**Comment by whykay** [comment]
I’d be happy to be on global nominations group - “ Nomination Selection” — Vicky Twomey-Lee (PyLadies Dublin)

**Comment by lorenanicole** [comment]
@whykay I've added you there! I'm going to change you permissions on this repo to contributor since I think you're not in there heh. Once you've accepted can you open a tracker issue (here's an example https://github.com/pyladies/global-organizing/issues/59) to help us get started? I'd say just dump any unit of work you think makes sense to be done for that thing. We can get a meeting or slack chat going once we have that done.

**Comment by whykay** [comment]
Thanks for adding me. I'll try, with Chinese New Year coming up and a bunch of workshops in the coming week or so, I might not get to it till next week the earliest. /puts on thinking hat

**Comment by lorenanicole** [comment]
@whykay that sounds like an agreeable time line! I think having that opened before end of month is great since we need to start doing the work (e.g. writing the nomination form, deciding rubric for selection, etc) in Feb 2020.

**Comment by lorenanicole** [comment]
*Public Election*

* Should voting will be open to any registered PyLadies member?

Only voting members

* What happens if there are ties?

In the case of a tie, the directions are outline here: https://github.com/pyladies/pyladies-council-election#in-the-event-of-a-tie

* What tech should be used for voting?

Helios election

* Who will be the election authority? 

TBD

**Comment by sleepypioneer** [comment]
similar to the other issues relating to the global council, @lorenanicole could this issue be closed as it appears to have been moved to Done on the project board? Perhaps however there is a reason to keep the issue open?
