### ISSUE TITLE
Website Update

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#6]
## Overview

Our PyLadies website is super outdated. It needs love.

## Scope of Work

*Phase 1*
- [ ] Theme and wireframe
- [ ] A review of what content do we want to keep and what do we want to add
- [ ] What tech do we want to use to build this? 
- [ ] Transfer pyladies.com domain and infra to Python Software Foundation / Ernest!

*Phase 2*
- We should hire someone from PyLadies to do this work! How do want to communicate the call?

**Comment by lorenanicole** [comment]
@RachellCalhoun are you interested in helping with this?

**Comment by lorenanicole** [comment]
@econchick / @estherbester can you please work with @Mariatta to get this infra reassigned?

**Comment by RachellCalhoun** [comment]
@lorenanicole, happy to help with this!

**Comment by primuse** [comment]
@lorenanicole, I'll be happy to help with this also.

**Comment by trallard** [comment]
I'd like to help with the content auditing. We might want to look at automating the addition of the chapters to the global map displayed instead of this being manual and being easily outdated
