### ISSUE TITLE
PyLadies Website: Framework Decision

### ISSUE THREAD

**Issue by mUtterberg** [pyladies/global-organizing#61]
Per https://github.com/pyladies/pyladies/issues/161, and as mentioned in #6 , we have been considering a new framework for the PyLadies website.

The two main candidates are
- Pelican (static)
- Wagtail (dynamic)

- [ ] The action item for this issue is to decide between these frameworks.
- [ ] A follow-up item would be to create a project proposal issue outlining steps to implement.

Summary of pros/cons for each ported over from the issue linked above:

# Pelican review

## Pros

Far less babysitting in terms of security vulnerabilities and potential ddos'ing
Actively maintained
PyLadies.com was originally on Pelican
Low barrier to entry
Some local chapters already use

## Cons

Not a full-featured CMS

# Wagtail review

## Pros

Extensible
User-friendly CMS
Based on Python3
Based on Django LTS

## Cons

Based on Django which adds complexity over a static site

**Comment by Mariatta** [comment]
Con with something like wagtail / django is that we need to host it somewhere on the cloud. Unless we already have something in place? 

With static website like pelican, it can just be hosted for free as GitHub pages.

**Comment by mUtterberg** [comment]
We use Pelican on GitHub Pages for our local chapter's website. For the global site, would the 1GB site limit [per GH Pages docs](https://help.github.com/en/github/working-with-github-pages/about-github-pages) be enough?  I'm not at a computer or I'd clone the current site's repo for a guesstimate.

**Comment by Mariatta** [comment]
Currently the size of https://github.com/pyladies/pyladies is 110.5 MB

**Comment by mUtterberg** [comment]
Fun fact: the issue that started this discussion was 161 and this issue is 61. Neat! Also, user @Mindiell posted [an update in the previous thread](https://github.com/pyladies/pyladies/issues/161) about having updated Mynt to modern Python.

I'm still hoping for us to move to Pelican, pending consensus, but this sounds like a possible way to extend the relevance life of the Mynt-ness.

**Comment by Mariatta** [comment]
I also prefer Pelican myself. The existing website doesn't have backend code, so switching to another static-site generator is easier effort. We'll also have to look at each chapter's individual websites that we host in the same repo and see what tech they're using, and coordinate with them.

cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
I'm 👍  pelican, I personally use that for my website
