### ISSUE TITLE
Monthly PyLadies Meeting Notes: May 13 2020

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#68]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

# PyLadies Global Meeting

- Date: May 13 2020
- Previous meeting issue link: https://github.com/pyladies/global-organizing/issues/66
- Current meeting attendees:
   @lorenanicole 
   @deboraazevedo
   @BethanyG 
   @biancarosa
   @georgically
   @AbigailDogbe 
   @amadikwa
   

## Agenda

_Please add items as needed. If you add a topic please make sure to attend the meeting._

### Project Updates
1. Project Comms (Slack: #project-communication / Repo: https://github.com/pyladies/project-communications)
    - Onboarding ongoing - we’re a relatively new team
    - Revamp blog - thinking through platforms (Pelican, Medium, Django)
    - Thinking about content and messaging
    - Election communications 
    - Looking at platforms for sending monthly newsletters
    - Friday meeting (5/15) for additional members

2. Project Admin & Logistics (Slack: #project-admin-logistics / Repo: https://github.com/pyladies/project-admin-logisitics )
    - We continue to use automation for new chapters (sync-up needed w/Mariatta)

3. Project Tech & Infra (Slack: #project-tech-infra / Repo: https://github.com/pyladies/pyladies )
    - We need more reviewers!  We need to think through PR review processes, and also recruit more 
       people to work on initiatives.
    - Mariatta & Lorena to sync up and talk through possible processes.

### Review Actions Items from Last Meeting

Action Item| Owner | Relevant links | Completed
| --| --| --| --|

### New Business

- [ ] #59 
       - Write the nomination application form
       - Write form to collect names for election
       - Write blog post for outreach
       - Translation
- [ ]
- [ ]
- [ ]
- [ ]

### Old Business: Follow up items from prior meeting:
  - [ ]
  - [ ]
  - [ ]
  - [ ]

### Action Items and Assignees for Next Meeting

Action Item| Owner | Relevant links | 
| --| --| --|

@pyladies/pyladies-global-contributors 
@pyladies/pyladies-global-admin

**Comment by Marie-L** [comment]
hey @lorenanicole could you please grant me permission to edit ?
