### ISSUE TITLE
PyLadies Project Proposal: Sponsorship

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-organizing#69]
# Project Proposal

A team to own sponsorships to PyLadies

## Is this a new project?

- [x] Yes
- [ ] No

## What is the name and focus area of this project?

Formalize process on how to sponsor PyLadies, costs, and benefits.

Some ideas:
- companies want to share their job posting with PyLadies network. What should we ask in return? We shouldn't have to spend free volunteer time to advertise companies. But some of our members do want to find job. We should have a way to facilitate this. How do we share it? Should we have mailing list just for PyLadies who want to receive job postings? Maybe work with both comms and finance team?
- conferences want to share their event with PyLadies network, share discount codes, etc. Same questions as above. What are the guidelines?

## Who will be the team member(s)?

Name | GitHub Handle | PyLadies Chapter | Team Role |
| --| --| --| --|
| Lorena Mesa | @lorenanicole | Chicago | Member |

## What are the initial unit(s) of work the project will target?

- form a team
- come up with sponsorship tiers

## Is there anything else relevant to the scope of this project?

cc/ @pyladies/pyladies-global-admin

**Comment by Mariatta** [comment]
I created this as I think this is important, but I'm not able to work on this right now.

**Comment by lorenanicole** [comment]
I'm very interested in this but don't have bandwidth _right this moment_. I can revisit in July.

**Comment by BethanyG** [comment]
Closing, as stale.
