### ISSUE TITLE
How do we approve PyLadies chapters?

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#7]
## Overview
We don't have a clear policy for how to approve a PyLadies chapter. As of now we have started:

- [X] @Mariatta has started working on automating chapter creation with bots
- [X] @elainewong and @Mariatta have taken over info@pyladies.com to respond to new chapter requests

### Scope of work

- [ ] What is our policy for approving PyLadies? Do we need a way to vet requests?
- [ ] When do we approve PyLadies chapters?
- [ ] Who approves PyLadies chapters?

### Temporary Response

- We will approve on a monthly frequency at our global meeting using @Mariatta and @elainewong list they are tracking for incoming requests

**Comment by primuse** [comment]
We do need a way to vet requests as some people might make those requests with no plan or commitment to grow the community. I suggest requiring prospective chapter organizers to provide recommendations/references from already existing chapter organizers. This I believe would help make sure that new chapters that open are sustained and don't become inactive after some time..

**Comment by Mariatta** [comment]
I agree that it would be great to hear more about their commitment.
However I feel that requiring recommendation from existing chapter leaders can be a barrier, and may be seen as lack of trust from our part.

I think there are other ways to show commitment though, other than getting references.

Some ideas are:
- provide plan/ideas of how they'll run their meetup for the next year, or
- provide plan on recruiting co-organizers, or
- provide examples of other involvements in community

**Comment by lorenanicole** [comment]
@Mariatta this sounds like something like updating the pyladies-kit with said resources!

**Comment by jackiekazil** [comment]
To be explicit, what problem are we trying to solve?

**Comment by lorenanicole** [comment]
@jackiekazil right now @mariatta has added automation to this but basically we don’t want to just blindly approve. For example we need to confirm there isn’t already an active chapter. So the problem we have to solve is precisely that: what steps do we need to take to confirm a chapter is valid to create?

**Comment by Mariatta** [comment]
I'd also want to know what would be the policy of who get to be organizers. Are we ok with men becoming PyLadies organizers?

I also think it would help prospective organizers if we can answer the following:
- what does it even mean to run a PyLadies chapter? What are our expectation from a PyLadies chapter? Is hosting meetup a must, or optional?  
- what kind of support can they expect from global PyLadies? Can they expecting funding from us? Compensation? Training resources?
Once we have those defined, I think we might need to adjust the "new chapter" form so we can capture the necessary info. E.g. if we require women as the organizer, we might have to ask for gender in the form, instead of guessing based on the submitter's name.

**Comment by jackiekazil** [comment]
RE: Men as leaders -- PyLadies CZ was started by men, I believe. As women became more active they were empowered by the men. (I am grossly summarizing it, but that might be a good group to check in with when thinking about guard rails or non-guard rails.) https://pyladies.cz/

**Comment by willingc** [comment]
It might make sense to have men be at most "interim" organizers or "startup" organizers.

**Comment by lorenanicole** [comment]
@Mariatta has started communication of these items in the https://github.com/pyladies/project-admin-logisitics/issues specifically:

- How to start a chapter: https://github.com/pyladies/project-admin-logisitics/issues/8
- Country specific chapter: https://github.com/pyladies/project-admin-logisitics/issues/9
- How to deactivate a chapter: https://github.com/pyladies/project-admin-logisitics/issues/10
- How to make "unofficial" chapters official: https://github.com/pyladies/project-admin-logisitics/issues/11

Everyone here should weigh in @willingc @jackiekazil @primuse!
