### ISSUE TITLE
Create the PyLadies Global Council wiki

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-organizing#73]
As we begin the election and nomination process, I think it would be great to document some of the challenges faced by PyLadies and the things that the global board need to address.

Some topics on my mind.

- PyLadies finance
Each year at PyCon PyLadies auction raises a substantial amount of money. Where does that money go? Can the money be used to support local groups? 

- PyLadies code of conduct and enforcement
How can global PyLadies help support and enforce code of conduct issues for local groups?

- PyLadies job board
Companies want to reach diverse audience and they want to share their job postings with PyLadies. We don't have formal job board, and I don't think we should advertise companies for free. Additionally, our members have a certain trust in PyLadies that any jobs posted by us can be seen as an endorsement. I think we need to establish a guideline for sharing job postings with our members.

Those are some of the things that I wish are documented somewhere. I'm sure others have additional questions and concerns.

**Comment by whykay** [comment]
Hi Mariatta,

On Wed, Aug 19, 2020 at 7:35 PM Mariatta <notifications@github.com> wrote:

> As we begin the election and nomination process, I think it would be great
> to document some of the challenges faced by PyLadies and the things that
> the global board need to address.
>
> Some topics on my mind.
>
>    -
>
>    PyLadies finance
>    Each year at PyCon PyLadies auction raises a substantial amount of
>    money. Where does that money go? Can the money be used to support local
>    groups?
>    -
>
>    PyLadies code of conduct and enforcement
>    How can global PyLadies help support and enforce code of conduct
>    issues for local groups?
>
> Maybe an onboard remote training session via zoom? What to do, what steps
to take, how to handle issues and situations, etc.

>
>    -
>
>    PyLadies job board
>    Companies want to reach diverse audience and they want to share their
>    job postings with PyLadies. We don't have formal job board, and I don't
>    think we should advertise companies for free. Additionally, our members
>    have a certain trust in PyLadies that any jobs posted by us can be seen as
>    an endorsement. I think we need to establish a guideline for sharing job
>    postings with our members.
>
> Women Who Code and Lesbians Who Tech charge companies to advertise jobs.
But certainly, if a PyLadies member submits a job, it's like a word of
mouth, like you said an endorsement, this should not be charged.
Also dev.to has an interesting way, they rewards points or you can buy
points for listings to promote things like jobs, courses, etc.

Cheers,

/// Vicky Twomey-Lee (PyLadies Dublin <https://twitter.com/pyladiesdub>
 Founder)
Pronouns: she/her/hers

Python Ireland <http://python.ie/> Member
EuroPython Member <http://www.europython-society.org/members> | PSF member
<http://pyfound.blogspot.ie/2012/08/welcome-new-psf-members.html>

**Comment by reshamas** [comment]
@Mariatta @whykay 
I am close to procuring a job board for my other meetup group, Data Umbrella.
I'll let you all know how it goes; if it works well, it would be a good option for PyLadies too.

**Comment by amcasari** [comment]
+1 to increased transparency for PyLadies finance. As a first step, I'd appreciate seeing it broken out separately in the PSF annual financial report.

**Comment by sleepypioneer** [comment]
@Mariatta could these be split into sub ISSUEs or have individual tasks on this issue then perhaps we can start with those that have available information and later tackle larger tasks such as a job board?

**Comment by BethanyG** [comment]
@sleepypioneer  -- this is a very old issue at this point.  While it has good discussion, I am not sure we're moving forward with a wiki at this point.  I think it might be better to close this and open newer issues as they come up.  We can refer back to this issue or link to it and its comments as needed.
