### ISSUE TITLE
Brainstorm global council's purpose, mission, and main responsibilities.

### ISSUE THREAD

**Issue by MmeMarieLouise** [pyladies/global-organizing#77]
Lynn:

This task doesn't need to generate the entire purpose, mission, etc. Just create a document, populate with some initial ideas, and start the asynchronous conversation/collaboration.

Google has a ["setting a team vision"](https://rework.withgoogle.com/guides/managers-set-and-communicate-a-team-vision/steps/create-a-vision-with-the-team/) guide that goes into purpose, mission, etc - which may help to at least start the conversation.

[PSF's structure & mission statement](https://www.python.org/psf/members/#id1).

**Task owner:** @Marie-L

**Comment by Marie-L** [comment]
Please find the document [here](https://docs.google.com/document/d/1PFY7vtL-mRsuSSONz12FFyaXBGnQJN8SFovbnEcubH8/edit?usp=sharing)

**Comment by Marie-L** [comment]
Thanks @econchick for updating this! @BethanyG @valerybriz @JUpani @trallard @julianafalves @Sonacrystal @cecivieira please add your ideas when you have time. Thanks!

**Comment by Marie-L** [comment]
Hey all, we are still waiting for @trallard @julianafalves @Sonacrystal @cecivieira to make a contribution. Please add your ideas when you have time. Thanks !

**Comment by julianafalves** [comment]
I've read the announcement and I like it. I don't have anything to add :).

**Comment by BethanyG** [comment]
Closing this since there has been no movement since 2021.  We can reopen, should we need to.
