### ISSUE TITLE
Start the PSF liaison process

### ISSUE THREAD

**Issue by Marie-L** [pyladies/global-organizing#86]

**Comment by trallard** [comment]
Hey @Marie-L I had also put myself up for this, let me know how I can help

**Comment by Marie-L** [comment]
Hey @trallard, sure! I stepped in just to get things moving. It would be great if we could arrange a meeting, I'll PM you on slack to find out your availability

**Comment by Marie-L** [comment]
We've got the ball rolling so I will close this issue
