### ISSUE TITLE
Liaise with PyLadies Paris about the PyLadies database of organizers

### ISSUE THREAD

**Issue by MmeMarieLouise** [pyladies/global-organizing#88]
PyLadies Paris organisers would like to understand more about the [PyLadies database of organisers]( https://docs.google.com/spreadsheets/d/14--69LWAGhF_DA8iPGRAOoh7GMJ3qFmcMQwASWqPo54/edit#gid=0)
- Can you please provide more information
- Also, please add them to the list

**Comment by BethanyG** [comment]
@Marie-L  - I'm pretty sure that that spreadsheet was a voluntary registry of organizers for public contact.  AFAK, the "official" registry, based on the survey/questionnaire sent out in 2019 that mapped organizers to "official" chapters, meetups, and emails is [here](https://docs.google.com/spreadsheets/d/1fK-wojdxHXicTzL-10VhzO7FkUY9Yc4oZblL3nLCg-U/edit#gid=1144100310).  I am a little worried that we have two different "databases".

**Comment by Marie-L** [comment]
@BethanyG, thank you for shedding more light on the situation ! Do you mind if I assign this to you as well?

**Comment by Marie-L** [comment]
Hey @JUpani and @BethanyG, please contact Maud and Maria at paris@pyladies.com or via slack (@Maud and @Maria Telenczuk) to discuss this further. Thanks !

**Comment by BethanyG** [comment]
Closing as outdated.
