### ISSUE TITLE
PyLadies Aug 15 2019 Email Communication 

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#9]
## Overview

Now that @Mariatta has a PyLadies Google admin account, we are building a master list of all PyLadies chapters from:

- Scraping MeetUp
- PyLadies Google admin view
- PyLadies Google form request to start a chapter form

Using this list on Aug 15 2019 the global team will be sending an email that'll include:

- Form collecting chapter data
- Update on PyLadies Global Governance #3 
- Update on website
- Update on resources including:
    - Archiving Google groups and IRC channel by Sept 15 2019
    - Using only PyLadies Slack from hereon in (with link to invite)
    - Reminder that organizers can join #organizers channel in PyLadies Slack and to tag @Mariatta , @elainewong , or @lorenanicole to get invited once in Slack
    - GitHub repo for Pyladies resources #5 
    - news about #global-feed PyLadies channel with info from PyLadies global meetings

### Work to be done

- [x] Draft language for email - https://docs.google.com/document/d/1N8TBmdaJlpC9iLHpuNiKUIGwqn2gEfdOVRYa2riLYw0/edit?usp=sharing
- [x] Update/review @katialira form to match the data points we need to collect:
    - Is the chapter active
    - If so, who are the organizers
    - Emails for organizers and chapter
    - Is your chapter interested in a personalized chapter PSF fundraising page? (pending approval from PSF)
    - Is your chapter interested in moving to PSF MeetUp account? (pending approval from PSF)
- [x] Get individual admin emails for @elainewong , @lorenanicole , @willingc (firstname@pyladies.com like @Mariatta ) and make `info@pyladies.com` a group admin account from @ewdurbin / PSF
- [x] @econchick make @lorenanicole admin for Google groups to announce retiring the Google group channels
- [x] @econchick to make @willingc @elainewong @lorenanicole Slack admins for PyLadies
- [x] @Mariatta to make `feed-monthly-minutes` for automatically publishing minutes into channel (we'll be sharing in the email)
- [x] Send email

**Comment by lorenanicole** [comment]
@ewdurbin today many of the PyLadies members met and were looking to get PyLadies admin emails setup like what @Mariatta has (`mariatta@pyladies.com`). Could you add for @willingc @elainewong and I?

**Comment by Mariatta** [comment]
Please also make (info@pyladies.com) an admin. We've been sharing access to that account. Thanks .

**Comment by ewdurbin** [comment]
> @ewdurbin today many of the PyLadies members met and were looking to get PyLadies admin emails setup like what @Mariatta has (`mariatta@pyladies.com`). Could you add for @willingc @elainewong and I?

@lorenanicole @willingc @elainewong please email ernest@python.org with your desired username on the pyladies domain.

**Comment by ewdurbin** [comment]
> Please also make ([info@pyladies.com](mailto:info@pyladies.com)) an admin. We've been sharing access to that account. Thanks .

I'd prefer it if we only granted administrator level permissions to named user accounts.

**Comment by ewdurbin** [comment]
Accounts created and invitation sent to @willingc, @elainewong, and @lorenanicole!

These users have also been granted access to manage the PyLadies organization in our GSuite.

**Comment by katialira** [comment]
1. First email to chapters that are already created.

Hello [chapter-leader],

We are conducting a small survey to better track the active PyLadies chapters. All you have to do is reply to this email and answer this short form.
[Link to google-forms]
Your answers and support will help us become a better, unified community.

Thank you so much,
PyLadies Lead Team

FORM QUESTIONS
When was your last event?
What are the challenges your chapter has faced?
How can the PyLadies leadership team help you run your chapter better?

List of receivers: [Form - Chapters Tab](https://docs.google.com/spreadsheets/d/126O2UKttJUzRyvd-Afgxz_cGn5bvbIIQTr9u_ItrXRM/edit?usp=sharing)

**Comment by katialira** [comment]
2. Email to people interested in running a chapter from a city without known chapter

Hello,

You are receiving this email because you showed interest in running a local PyLadies chapter. We want to follow up. All you have to do is reply to this email and answer this short form.
[Link to google-forms]

Your answers and support will help us become a better, unified community.

Thank you so much,
PyLadies Lead Team

FORM - Questions
Do you run a chapter in your community? Which one?
If not, are you still interested in running one?

List of receivers - [Form - Interested Tab](https://docs.google.com/spreadsheets/d/126O2UKttJUzRyvd-Afgxz_cGn5bvbIIQTr9u_ItrXRM/edit?usp=sharing)

**Comment by lorenanicole** [comment]
@katialira thanks for the above! By the way, what we are doing now is condensing the form questionnaire email into one email where we'll have several announcements. Email language is linked above in the issue but I'm pasting here again: https://docs.google.com/document/d/1N8TBmdaJlpC9iLHpuNiKUIGwqn2gEfdOVRYa2riLYw0/edit

Feel free to weigh in on the language if you think anything needs to be changed.

**Comment by Mariatta** [comment]
My plan is to send the same email content, containing both forms, to:
- {chapter}@pyladies.com, and
- personal email address used to sign up for new chapter
Emails will be sent via info@pyladies.com
